import { BsFillAirplaneFill } from 'react-icons/bs'
import { TbPlaneDeparture } from 'react-icons/tb'
import { IoEarthSharp } from 'react-icons/io'
import { FaLuggageCart } from 'react-icons/fa'
import { TbLuggage } from 'react-icons/tb'
import { GiSchoolBag } from 'react-icons/gi'
import { AiFillCar } from 'react-icons/ai'
import { FaUmbrellaBeach } from 'react-icons/fa'